# Gradle
org.gradle.jvmargs = -Xmx6G
org.gradle.parallel = true
org.gradle.daemon = false
fabric.loom.ignoreDependencyLoomVersionValidation = true
fabric.loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

# Project
mod_id = suppsquared
mod_name = Supplementaries Squared
mod_author = MehVahdJukaar, Plantkillable
mod_description = Additional block variations for Supplementaries
mod_version = 1.21-1.2.17
mod_license = Supplementaries Team License v.1.4
mod_authors = MehVahdJukaar, Plantkillable
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/suppsquared
mod_credits = Plantkillable, MehVahdJukaar
mod_github = https://github.com/MehVahdJukaar/suppsquared

release_type = release
maven_group = net.mehvahdjukaar

mc_version = 1.21.1

neoforge_version = 21.1.219

fabric_loader_version = 0.17.2
fabric_api_version = 0.116.6+1.21.1

parchment_mappings_version = 2024.11.17

# Publishing
repository = mehvahdjukaar/suppsquared
modrinth_project_id = supplementaries-squared
curseforge_project_id = 838411

# Other deps (versions aligned with cameramod / vista where the dependency overlaps)
moonlight_version = 1.21.1-3.0.6
moonlight_min_version = 1.21-2.29.17
supplementaries_version = 1.21.1-3.6.2
supplementaries_min_version = 1.21-2.9.0

mixin_squared_version = 0.1.1

cloth_version = 11.0.99
